### ISSUE TITLE
Critical-ish: Failed at finding and announcing newest community post.

### ISSUE THREAD

**Issue by lillelilje** [oleerik/rust-bot#1]
```
Logged in as
Rust-bot

Invite: https://discordapp.com/oauth2/authorize?client_id=&scope=bot
------
Initializing rss check for Rust
Most recent item:
Devblog 189
https://rust.facepunch.com/blog/devblog-189/
On list: <Redacted>
Task exception was never retrieved
future: <Task finished coro=<background_loop() done, defined at rust-bot.py:26> exception=IndexError('list index out of range',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "rust-bot.py", line 58, in background_loop
    if post != feed['entries'][0]:
IndexError: list index out of range

```

**Comment by lillelilje** [comment]
Error comes from these lines:
```
        try:
            feed = feedparser.parse(url)
        except:
            await asyncio.sleep(10)
            continue

        if post != feed['entries'][0]:
post = feed['entries'][0]
```

The try: clause will have to be made into a loop instead, to make sure that data is actually found.
That should resolve the issue.
